/**
 * Part B verification: runs the Part A harness (tools/lib/playtestEngine.ts)
 * against every hole in the course, not just HOLE_1. "Verify each new hole
 * with the Part A harness before considering it done" -- this is that
 * verification, plus the whole-course club-usage report Part B's report-back
 * asks for.
 *
 * Run: npm run course-playtest
 */
import { CLUBS } from "@mulligan/shot-source";
import { COURSE } from "@mulligan/game";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  analyzeClubUsage,
  fmtPct,
  hazardDistanceFromTee,
  mean,
  penaltyAttribution,
  runConfig,
  scoreDistribution,
} from "./lib/playtestEngine";

// Lower than Part A's single-hole deep dive (400) -- six holes x five
// configurations each adds up, and this pass is a per-hole sanity check
// plus a whole-course aggregate, not a precision study of any one hole.
const ROUNDS = 250;
const DOGLEG_LIVE_THRESHOLD = 0.1;
const TEE_DECISION_LIVE_THRESHOLD = 0.1;

function main() {
  const lines: string[] = [];
  lines.push("# Course playtest findings — all six holes");
  lines.push("");
  lines.push(`Generated by \`tools/course-playtest.ts\` (\`npm run course-playtest\`), ${ROUNDS} simulated rounds per configuration per hole, same policy definitions as \`docs/playtest-findings.md\`. HOLE_1 ("The Bend") is included for the whole-course numbers but its own findings are unchanged from Part A -- see that doc for the deep dive.`);
  lines.push("");

  const courseClubUsage: Partial<Record<string, number>> = {};
  let courseShots = 0;
  const holeSummaries: string[] = [];
  let anyPlaysItself = false;

  for (const hole of COURSE) {
    const par = hole.par;
    const smart = runConfig(hole, { aimPolicy: "smart" }, ROUNDS);
    const pinOnly = runConfig(hole, { aimPolicy: "pin" }, ROUNDS);
    const centerlineOnly = runConfig(hole, { aimPolicy: "centerline" }, ROUNDS);
    const alwaysDriver = runConfig(hole, { aimPolicy: "smart", teeShotOverride: "driver" }, ROUNDS);
    const layup = runConfig(hole, { aimPolicy: "smart", teeShotOverride: "layup" }, ROUNDS);

    const clubUsage = analyzeClubUsage(smart);
    const totalShots = Object.values(clubUsage).reduce((a, b) => a + b, 0);
    const unusedClubs = CLUBS.filter((c) => clubUsage[c.id] === 0).map((c) => c.name);
    for (const club of CLUBS) courseClubUsage[club.id] = (courseClubUsage[club.id] ?? 0) + clubUsage[club.id];
    courseShots += totalShots;

    const meanPin = mean(pinOnly.map((r) => r.totalStrokes));
    const meanCenterline = mean(centerlineOnly.map((r) => r.totalStrokes));
    const doglegMargin = Math.abs(meanPin - meanCenterline);

    const hazardDist = hazardDistanceFromTee(hole);
    const meanDriver = mean(alwaysDriver.map((r) => r.totalStrokes));
    const meanLayup = mean(layup.map((r) => r.totalStrokes));
    const teeMargin = Math.abs(meanDriver - meanLayup);

    const dist = scoreDistribution(smart, par);
    const penalties = penaltyAttribution(smart);
    const totalPenalties = [...penalties.values()].reduce((a, b) => a + b, 0);
    const failed = smart.filter((r) => r.failed).length;

    const doglegLive = doglegMargin >= DOGLEG_LIVE_THRESHOLD;
    const teeLive = hazardDist !== null && teeMargin >= TEE_DECISION_LIVE_THRESHOLD;
    const hasPenalties = totalPenalties > 0;
    const clubVarietyOk = unusedClubs.length < 2;
    const liveAxes = [doglegLive, teeLive, hasPenalties].filter(Boolean).length;
    const playsItself = liveAxes === 0 && !clubVarietyOk;
    if (playsItself) anyPlaysItself = true;

    lines.push(`## ${hole.name} (par ${par})`);
    lines.push("");
    if (failed > 0) lines.push(`**${failed}/${ROUNDS} rounds never finished (safety valve hit).**`);
    lines.push(`- Mean score: ${mean(smart.map((r) => r.totalStrokes)).toFixed(2)} (par ${par}); par-or-better ${fmtPct(dist.eagleOrBetter + dist.birdie + dist.par, ROUNDS)}, bogey ${fmtPct(dist.bogey, ROUNDS)}, double+ ${fmtPct(dist.doubleOrWorse, ROUNDS)}.`);
    lines.push(`- Line choice (pin vs. fairway centerline aim): ${doglegMargin.toFixed(2)} stroke difference ${doglegLive ? "-- live" : "-- decorative"}.`);
    lines.push(
      hazardDist === null
        ? "- No hazard on the direct tee-to-pin line -- driver-vs-layup isn't a meaningful comparison on this hole as authored."
        : `- Tee shot (driver vs. laying up short of the hazard ${hazardDist.toFixed(0)}yd out): ${teeMargin.toFixed(2)} stroke difference ${teeLive ? "-- live" : "-- decorative"}.`,
    );
    lines.push(`- Penalty strokes: ${totalPenalties} across ${ROUNDS} rounds ${hasPenalties ? "-- the hazard(s) draw real blood" : "-- never actually punished a shot"}.`);
    lines.push(`- Clubs never used: ${unusedClubs.length > 0 ? unusedClubs.join(", ") : "none"}.`);
    lines.push(
      playsItself
        ? "**This hole plays itself under this harness -- see the flat numbers above.**"
        : `Live: ${[doglegLive && "line choice", teeLive && "tee-shot risk", hasPenalties && "hazard consequence"].filter(Boolean).join(", ") || "club variety only"}.`,
    );
    lines.push("");

    holeSummaries.push(`${hole.name} (par ${par}): ${playsItself ? "plays itself" : "asks a real question"}`);
  }

  lines.push("## Club usage across the whole course");
  lines.push("");
  lines.push("| club | shots | % of all shots |");
  lines.push("|---|---|---|");
  const neverUsed: string[] = [];
  for (const club of CLUBS) {
    const n = courseClubUsage[club.id] ?? 0;
    if (n === 0) neverUsed.push(club.name);
    lines.push(`| ${club.name} | ${n} | ${fmtPct(n, courseShots)} |`);
  }
  lines.push("");
  lines.push(
    neverUsed.length > 0
      ? `**${neverUsed.length} club(s) never come out of the bag across all six holes: ${neverUsed.join(", ")}.**`
      : "Every club in the bag gets used somewhere on the course.",
  );
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  for (const s of holeSummaries) lines.push(`- ${s}`);
  lines.push("");
  lines.push(anyPlaysItself ? "**At least one hole still plays itself under this harness -- see above for which.**" : "**No hole plays itself under this harness: every hole has at least one live decision axis.**");
  lines.push("");

  writeFileSync(resolve(process.cwd(), "docs/course-playtest-findings.md"), lines.join("\n") + "\n");
  console.log(lines.join("\n"));
  console.log("\nWritten to docs/course-playtest-findings.md");
}

main();
